var analogies = [
    {
        "bouton": "Animal",
        "thème": "un animal",
        "reponse": "Un loup",
        "explain": "parce que j’aime cet animal depuis que je suis petite. A mes yeux, il est symbole de liberté, d’indépendance, de spontanéité mais aussi de sagesse.",
        "image": "img/loup.jpeg",
        "numéro": "a1",
    },
    {
        "bouton": "Art",
        "thème": "un art",
        "reponse": "La musique",
        "explain": "parce que je ne peux passer une journée sans écouter au moins une musique. Certains récupèrent de l’énergie auprès des autres, moi c’est en me créant une bulle en écoutant de la musique. De plus, la musique permet de transmettre des messages d’une nouvelle manière, c’est pourquoi je la trouve encore plus incroyable et importante.",
        "image": "img/music.jpg",
        "numéro": "a2",
    },
    {
        "bouton": "Élement",
        "thème": "un élément",
        "reponse": "Le feu",
        "explain": "parce que même si a première vue le feu pourrait ne paraître que négatif, le feu représente aussi la chaleur, la protection et la lumière. Il exprime une énergie à l’état brut. Je trouve cet élément assez fascinant. De plus, selon l’élément que nous brûlons la flamme peut changer de couleur, le zinc et le cuivre donnent du bleu, le sodium du jaune et le baryum du vert, ce que je trouve d’autant plus incroyable.",
        "image": "img/fire.jpg",
        "numéro": "a3",
    },
    {
        "bouton": "Livre",
        "thème": "un livre",
        "reponse": "L'étranger d'Albert Camus",
        "explain": "parce que je ne connais pas grand monde qui aiment et même qui ont lu ce livre, mais personnellement j’ai plutôt bien aimé. J’ai lu ce livre il y a un moment maintenant pourtant de nombreuses phrases me restent en mémoire, ce qui fait que c’est l’un de mes livres favoris.",
        "image": "img/livre.jpg",
        "numéro": "a4",
    },
    {
        "bouton": "Moment",
        "thème": "un moment de la journée",
        "reponse": "Le crépuscule",
        "explain": "parce que celui-ci arrive deux fois dans la journée mais ne dure pas longtemps à chaque fois. Pourtant la beauté de ce moment reste époustouflant à mes yeux. Le crépuscule, qu’il soit le matin ou le soir, ne dure qu’un court laps de temps, durant celui-ci le ciel se colore d’une multitude de nuances.",
        "image": "img/crepuscule.jpg",
        "numéro": "a6",
    },
    {
        "bouton": "Astre",
        "thème": "un astre",
        "reponse": "La lune",
        "explain": "parce que même si chaque fois que le soleil apparaît, elle disparaît, elle est toute aussi importante. Elle contrôle la marée, les eaux et les saisons. Même si elle est dans l’ombre du soleil, et que la moitié de sa surface est encore inconnu, elle nous fascine, elle me fascine, et nous continuons chaque jour de vouloir découvrir ses secrets. Souvent, j’aime bien me poser quelque part et regarder la lune et les étoiles lorsqu’il fait nuit.",
        "image": "img/moon.jpg",
        "numéro": "a5",
    },
    {
        "bouton": "Scientifique",
        "thème": "un scientifique célèbre",
        "reponse": "Stephen Hawking",
        "explain": "parce que je trouve son histoire incroyable ! Atteint de la maladie de Charcot, les médecins ne lui donnaient seulement quelques années, pourtant Stephen Hawking ne s’est pas laissé abattre (pendant une période si mais il s’est ressaisi). Il a continué à faire ses recherches et partager ses théories et découverte. Même avec sa maladie qui s’aggravait de jour en jour et la mort qui pouvait venir d’un moment à l’autre, il a continué à faire ce qu’il aimait, ainsi que vivre et rire.",
        "image": "img/stephen.jpeg",
        "numéro": "a7",
    },
]
